services:
  docling-converter:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./dataset:/app/dataset
      - ./scratch:/app/scratch
      - docling_cache:/root/.cache

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    command: ["python", "document_converter.py", "/app/dataset", "--output_dir", "/app/scratch"]

  langchain-chunker:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./scratch:/app/scratch
      - docling_cache:/root/.cache
    
    command: ["python", "create_chunks.py", "/app/scratch/4x-strategy.json", "--output_json", "/app/scratch/langchain_chunks.json"]

volumes:
  docling_cache: