services:
  docling-converter:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./dataset:/app/dataset
      - ./scratch:/app/scratch
      - docling_cache:/root/.cache

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    command: ["python", "document_converter.py", "/app/dataset", "--output_dir", "/app/scratch"]
  
  vector-store:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./scratch:/app/scratch
      - ./vector-db:/app/vector-db
      - docling_cache:/root/.cache
    
    command: ["python", "vector_store.py", "/app/scratch", "--persist_directory", "/app/vector-db", "--initial_k", "20", "--final_k", "5"]
    depends_on:
      - docling-converter

  agent:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./scratch:/app/scratch
      - ./vector-db:/app/vector-db
      - ./json:/app/json
      - docling_cache:/root/.cache
    
    command: ["python", "agent.py", "--persist_directory", "/app/vector-db", "--output_dir", "/app/json"]
    depens_on:
      - vector-store
  
  init_db:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./json:/app/json
      - .:/app
    command: ["python", "init_db.py", "--json", "/app/json/competitor_intelligence.json", "--db", "/app/database.db"]
    depends_on:
      - agent

  api:
    build: .
    env_file:
      - .env
    volumes:
      - ./json:/app/json
      - .:/app
    ports:
      - "8000:8000"
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - init_db

volumes:
  docling_cache: