services:
  docling-converter:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./dataset:/app/dataset
      - ./scratch:/app/scratch
      - docling_cache:/root/.cache

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    command: ["/app/dataset", "--output_dir", "/app/scratch"]

volumes:
  docling_cache: